server:
  port: 31275
  servlet:
    context-path: /api/v1

spring:
  application:
    name: music-server
  data:
    redis:
      host: redis-13386.c240.us-east-1-3.ec2.redns.redis-cloud.com
      port: 13386
      database: 0
      # password:  # Set if needed
      password: 64aT1owqS7Klf6053SYdIu3FAvN7G0dl
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  music:
    base-path: /tmp/music_plan
    # Derived paths
    data-file: ${app.music.base-path}/db/music_data.json
    user-file: ${app.music.base-path}/db/user_data.json
    files-dir: ${app.music.base-path}/files/
    covers-dir: ${app.music.base-path}/covers/
  auth:
    username: dihuangkaijia
    token-ttl-days: 7

logging:
  level:
    com.music.server: DEBUG
